name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run Tests on Multiple Environments
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [18, 20, 21]
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm ci

      - name: Run Tests
        run: npm test

  deploy:
    name: Deploy to AWS EC2
    runs-on: ubuntu-latest
    needs: test # Ensure deployment happens only if tests pass

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/ci-cd-key
          chmod 600 ~/.ssh/ci-cd-key
          ssh-keyscan 44.201.195.99 >> ~/.ssh/known_hosts

      - name: Deploy to AWS EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/node-ci-cd || git clone https://github.com/Joy-it-code/node-ci-cd-2.git ~/node-ci-cd-2
            cd ~/node-ci-cd-2
            git pull origin main
            npm install
            pm2 restart index.js || pm2 start index.js --name "node-app"